### 1. Data Loading + Preparing

In [1]:
import pandas as pd

pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv("../data/raw/pfaf_plants_merged.csv")
path = "/Users/kubrademirhan/Documents/smart_herb_recommendation_system/data/raw/pfaf_plants_merged.csv"
data = pd.read_csv(path)

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 17950 entries, 0 to 17949
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   use_keyword              17950 non-null  str
 1   latin_name_search        17950 non-null  str
 2   common_name_search       16132 non-null  str
 3   edibility_rating_search  17950 non-null  int64
 4   medicinal_rating_search  17950 non-null  int64
 5   plant_url                17950 non-null  str
 6   Care Requirements        14283 non-null  str
 7   Common Name              12700 non-null  str
 8   Common Names             12700 non-null  str
 9   Cultivation Details      14281 non-null  str
 10  Edibility Rating         14283 non-null  float64
 11  Edible Uses              14283 non-null  str
 12  Family                   14283 non-null  str
 13  Image URLs               14283 non-null  str
 14  Known Hazards            14283 non-null  str
 15  Medicinal Properties     14283 non-null  str
 16  Medicinal Rating         14283 non-null  float64
 17  Native Range             14256 non-null  str
 18  Other Uses               14283 non-null  str
 19  Other Uses Rating        14283 non-null  float64
 20  Propagation              14266 non-null  str
 21  Range                    14274 non-null  str
 22  Scientific Name          14283 non-null  str
 23  Special Uses             8266 non-null   str
 24  Summary                  5920 non-null   str
 25  USDA hardiness           14283 non-null  str
 26  Weed Potential           14283 non-null  str
dtypes: float64(3), int64(2), str(22)
memory usage: 54.8 MB

In [4]:
data.columns

Index(['use_keyword', 'latin_name_search', 'common_name_search',
       'edibility_rating_search', 'medicinal_rating_search', 'plant_url',
       'Care Requirements', 'Common Name', 'Common Names',
       'Cultivation Details', 'Edibility Rating', 'Edible Uses', 'Family',
       'Image URLs', 'Known Hazards', 'Medicinal Properties',
       'Medicinal Rating', 'Native Range', 'Other Uses', 'Other Uses Rating',
       'Propagation', 'Range', 'Scientific Name', 'Special Uses', 'Summary',
       'USDA hardiness', 'Weed Potential'],
      dtype='str')

In [5]:
data['Medicinal Properties'].head(20)

0                                                                                                                                             Antihalitosis; Antispasmodic; Aphrodisiac; Appetizer; Aromatherapy; Digestive; Nervine; Stomachic; Vulnerary
1                                                                                                                                                                                          Antirheumatic; Laxative; Ophthalmic; Skin; Stomachic; TB; Tonic
2                                                                                                                                                                                     Antiperiodic; Astringent; Carminative; Expectorant; Stomachic; Tonic
3                                                                                                                                                Astringent; Demulcent; Diuretic; Dysentery; Emollient; Laxative; Ophthalmic; Poultice; Stomachic; Urinary
4                                                                                                                                                                                                    Astringent; Demulcent; Dysentery; Poultice; Stomachic
5                                                                                                                                                                                            Appetizer; Diaphoretic; Digestive; Diuretic; Stomachic; Tonic
6                                                                                                                                                                                                                            Carminative; Stomachic; Tonic
7                                                                                                                                                     Antibacterial; Antiinflammatory; Carminative; Diaphoretic; Emmenagogue; Odontalgic; Stomachic; Tonic
8                                                                                                                                                                                                             Diuretic; Odontalgic; Rubefacient; Stomachic
9                                                                                                                                                                                                                                                Stomachic
10                                      Abortifacient; Anodyne; Antirheumatic; Aphrodisiac; Aromatic; Carminative; Diaphoretic; Emmenagogue; Epilepsy; Febrifuge; Hallucinogenic; Homeopathy; Odontalgic; Sedative; Stimulant; Stomachic; Tonic; Vermifuge
11    Anodyne; Antibacterial; Antifungal; Antiperiodic; Antirheumatic; Antispasmodic; Aromatic; Cardiac; Carminative; Diaphoretic; Diuretic; Emmenagogue; Epilepsy; Expectorant; Febrifuge; Parasiticide; Sedative; Stimulant; Stomachic; Tonic; Vermifuge
12                                                                                                                                                    Antidote; Antifungal; Cardiotonic; Expectorant; Febrifuge; Sialagogue; Stomachic; Women's complaints
13                                                                                                                                                                                     Acrid; Anthelmintic; Antirheumatic; Astringent; Narcotic; Stomachic
14                                                                                                                                                                                                     Anticonvulsant; Antidiarrhoeal; Sedative; Stomachic
15                                                                                                                                                                                                                                      Cardiac; Stomachic
16                                                                                                                                                                                                                                      Cardiac; Stomachic
17                                                                                                                                                                                                                                      Cardiac; Stomachic
18                                                                                                                                   Antibacterial; Antifungal; Antipyretic; Aromatic; Cancer; Carminative; Diaphoretic; Febrifuge; Refrigerant; Stomachic
19                                                                                                                                                                                                                     Analgesic; Antirheumatic; Stomachic
Name: Medicinal Properties, dtype: str

In [6]:
columns_to_drop = [
    'use_keyword',
    'latin_name_search',
    'common_name_search',
    'edibility_rating_search',
    'medicinal_rating_search',
    'plant_url',
    'Image URLs',
    'Cultivation Details',
    'Propagation',
    'Range',
    'Native Range',
    'USDA hardiness',
    'Weed Potential'
]

In [7]:
data = data.drop(columns=columns_to_drop)

In [8]:
data.columns

Index(['Care Requirements', 'Common Name', 'Common Names', 'Edibility Rating',
       'Edible Uses', 'Family', 'Known Hazards', 'Medicinal Properties',
       'Medicinal Rating', 'Other Uses', 'Other Uses Rating',
       'Scientific Name', 'Special Uses', 'Summary'],
      dtype='str')

In [9]:
data["user_need_tags"] = " "
data["effect_tags"] = " "
data["preparation_type"] = " "
data["recommendation_score"] = 0.0
data["warning_level"] = " "
data["recommendation_reason"] = " "

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 17950 entries, 0 to 17949
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Care Requirements      14283 non-null  str
 1   Common Name            12700 non-null  str
 2   Common Names           12700 non-null  str
 3   Edibility Rating       14283 non-null  float64
 4   Edible Uses            14283 non-null  str
 5   Family                 14283 non-null  str
 6   Known Hazards          14283 non-null  str
 7   Medicinal Properties   14283 non-null  str
 8   Medicinal Rating       14283 non-null  float64
 9   Other Uses             14283 non-null  str
 10  Other Uses Rating      14283 non-null  float64
 11  Scientific Name        14283 non-null  str
 12  Special Uses           8266 non-null   str
 13  Summary                5920 non-null   str
 14  user_need_tags         17950 non-null  str
 15  effect_tags            17950 non-null  str
 16  preparation_type       17950 non-null  str
 17  recommendation_score   17950 non-null  float64
 18  warning_level          17950 non-null  str
 19  recommendation_reason  17950 non-null  str
dtypes: float64(4), str(16)
memory usage: 24.2 MB

In [11]:
data.head(3)

,Care Requirements,Common Name,Common Names,Edibility Rating,Edible Uses,Family,Known Hazards,Medicinal Properties,Medicinal Rating,Other Uses,Other Uses Rating,Scientific Name,Special Uses,Summary,user_need_tags,effect_tags,preparation_type,recommendation_score,warning_level,recommendation_reason
0,Moist Soil; Half Hardy; Full sun,"Musk Mallow,Musk Okra","Musk Mallow,Musk Okra",2.0,"Edible Parts: Leaves Oil Root Seed Seedpod Shoots Edible Uses: Condiment Oil Young leaves and shoots - cooked in soups[183, 272]. Used as a vegetable[238]. The leaves are also used to clarify sugar[183]. Unripe seedpods - cooked as a vegetable in much the same way as okra (A. esculentus)[183, 238, 272]. Seed - cooked[272]. It is fried or roasted and has a flavour similar to sesame seeds[272]. The seed is also used as a flavouring for liqueurs or to scent coffee[183, 238]. An essential oil is obtained from the plant and is used to flavour baked goods, ice cream, sweets and soft drinks[183]. Root[183]. No more details are given, though the root is likely to have a bland flavour and a fibrous texture.",Malvaceae,None known,Antihalitosis; Antispasmodic; Aphrodisiac; Appetizer; Aromatherapy; Digestive; Nervine; Stomachic; Vulnerary,3.0,"Essential Fibre Insecticide Oil Size An essential oil is obtained from the plant[238]. It is used as a food flavouring and in perfumery as a musk substitute[238]. However, it has been known to cause photosensitivity so this use has been largely discontinued[238]. An oil obtained from the seed contains 18.9% linoleic acid[240]. The oil is f high econmic value[266]. Total yields of oil are not given[K]. The seeds are used as an insecticide[4, 238]. Another report says that extracts of the fruits and upper parts of the plant show insecticidal activity[240]. A fibre is obtained from the stem bark[238]. It is used to make ropes[272]. A mucilage obtained from the roots is used as a size for paper[238].",3.0,Abelmoschus moschatus - Medik.,Scented Plants,NaN,,,,0.0,,
1,Semi-shade; Fully Hardy; Moist Soil; Full shade; Full sun,"Grand Fir, Giant Fir, Lowland White Fir","Grand Fir, Giant Fir, Lowland White Fir",2.0,"Edible Parts: Inner bark Shoots Edible Uses: Drink Gum Tea Inner bark - cooked. It is usually dried, ground into a powder and then used as a thickening in soups etc or mixed with cereals when making bread[161]. It is best used in the spring when it is rich and juicy[213]. An emergency food, it is only used when all else fails[183]. The gum from the trunk is hardened (probably in cold water[K]) and used as a chewing gum[257]. It can also be made into a drink[257]. Young shoot tips are used as a tea substitute[183, 257].",Pinaceae,None known,Antirheumatic; Laxative; Ophthalmic; Skin; Stomachic; TB; Tonic,2.0,"Baby care Dye Gum Incense Repellent Roofing Wood The aromatic leaves are used as a moth repellent[169]. The boughs have been used in the home as an incense[257]. A pink dye can be obtained from the bark[226]. The dried and hardened pitch can be chewed as a tooth cleanser[257]. A powder made from the dried and crushed leaves was used as a baby powder by the N. American Indians[226]. The bark can be used as a waterproof covering material for buildings and canoes[257]. Wood - light, soft, coarse grained, not strong, not very durable. Used for interior work, cases, etc[46, 61, 82]. Of little value as a lumber, it is used mainly for pulp and fuel[229, 257].",3.0,Abies grandis - (Douglas. ex D.Don.)Lindl.,Food Forest Scented Plants,"Form: Columnar, Upright or erect.",,,,0.0,,
2,Semi-shade; Fully Hardy; Moist Soil; Full shade; Full sun,Himalayan Fir,Himalayan Fir,0.0,None known,Pinaceae,None known,Antiperiodic; Astringent; Carminative; Expectorant; Stomachic; Tonic,2.0,"Essential Fuel Incense Wood An essential oil is obtained from the plant, though the report does not give yields or uses[240]. The dried leaves, mixed with other ingredients, are used in making incense[272]. The wood is used for construction and thatching roofs[272]. It is also used for fuel[272].",3.0,Abies spectabilis - (D.Don.)Spach.,Scented Plants,NaN,,,,0.0,,

### 2. Feature Engineering + Curating

In [12]:
filtered_data = data.dropna(subset=["Medicinal Properties"])

filtered_data.shape

(14283, 20)

In [13]:
target_plants = [
    "Chamomile", "Lavender", "Peppermint", "Lemon Balm", "Ginger",
    "Turmeric", "Sage", "Rosemary", "Eucalyptus", "Aloe Vera",
    "Valerian", "St John's Wort", "Nettle", "Fennel", "Thyme",
    "Garlic", "Cinnamon", "Dandelion", "Passionflower", "Ginkgo"
]

In [14]:
mvp_data = filtered_data[
    filtered_data["Common Name"].str.contains(
        "|".join(target_plants),
        case=False,
        na=False
    )
].copy()

In [15]:
mvp_data[["Common Name", "Scientific Name", "Medicinal Properties", "Known Hazards"]].head(50)

,Common Name,Scientific Name,Medicinal Properties,Known Hazards
8,Basil Thyme,Acinos arvensis - (Lam.)Dandy.,Diuretic; Odontalgic; Rubefacient; Stomachic,None known
19,"Giant Hyssop, Nettleleaf giant hyssop",Agastache urticifolia - (Benth.)Kuntze.,Analgesic; Antirheumatic; Stomachic,None known
28,"Garlic, Cultivated garlic",Allium sativum - L.,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Hypoglycaemic; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]. Avoid with anticlotting medication. Breastfeeding may worsen baby's colic. Avoid several weeks prior to surgery. Bad breath!! [301]."
29,Serpent Garlic,Allium sativum ophioscorodon - (Link.)Döll.,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]."
30,"Garlic Chives, Chinese chives, Oriental Chives,",Allium tuberosum - Rottler. ex Spreng.,Antibacterial; Cardiac; Digestive; Stomachic; Tonic; Urinary,"Although no individual reports regarding this species have been seen, there have been cases of poisoning caused by the consumption, in very large quantities and by some mammals, of certain members of this genus. Dogs seem to be particularly susceptible[76]."
31,Wild Garlic,Allium ursinum - L.,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Astringent; Cholagogue; Depurative; Diaphoretic; Disinfectant; Diuretic; Expectorant; Febrifuge; Hypotensive; Rubefacient; Stimulant; Stomachic; Tonic; Vasodilator,"There have been cases of poisoning caused by the consumption, in very large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]."
38,"Aloe Vera, Barbados aloe, First Aid Plant, Medicinal Aloe",Aloe vera - (L.)Burm.f.,Cancer; Emmenagogue; Emollient; Laxative; Miscellany; Purgative; Skin; Stimulant; Stomachic; Tonic; Vermifuge; Vulnerary,"Taken by mouth may cause cramping pain in the gastrointestinal tract and diarrhoea (reduce dose). Skin rashes with long term use of gel. Rare adverse effects are on heart rhythm, kidney damage and oedema. Long term use can cause electrolytes loss esp. potassium and may therefore enhance the effect of drugs that act on the heart (e.g. digoxin) [301]."
63,"Sand Sage, Sand sagebrush",Artemisia filifolia - Torr.,Carminative; Miscellany; Stomachic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]."
64,"Fringed Wormwood, Prairie sagewort",Artemisia frigida - Willd.,Antispasmodic; Deodorant; Disinfectant; Poultice; Stimulant; Stomachic; Vermifuge; Women's complaints,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]."
72,"Snake Root, Canadian wildginger, Canada Wild Ginger, Wild Ginger",Asarum canadense - L.,Anthelmintic; Antiasthmatic; Antibiotic; Antitumor; Carminative; Contraceptive; Diaphoretic; Diuretic; Expectorant; Irritant; Poultice; Salve; Stimulant; Stomachic; Tonic,The leaves are poisonous[19]. Handling the leaves is said to cause dermatitis in some people[269].
73,"Wild Ginger, British Columbia wildginger",Asarum caudatum - Lindl.,Analgesic; Antirheumatic; Appetizer; Laxative; Poultice; Stomachic; Tonic,"Although no reports of toxicity have been found for this plant, at least 3 other members of this genus have reports that the leaves are toxic[7, 19]. Some caution is therefore advised in the use of this plant."
112,"Nettle Tree, European hackberry",Celtis australis - L.,Astringent; Dysentery; Lenitive; Stomachic,None known
121,"Chamomile, Roman chamomile",Chamaemelum nobile - (L.)All.,Anodyne; Antianxiety; Antiinflammatory; Antispasmodic; Aromatherapy; Nervine; Stomachic; Tonic; Vasodilator,"Patients with severe allergic responses to ragweed (ragwort) should be warned about the possible cross-sensitivity to chamomile and other members of the Asteraceae/Compositae family (e.g. echinacea, feverfew, milk thistle)."
177,"Antelope Sage, James' buckwheat",Eriogonum jamesii - Benth.,Analgesic; Cardiac; Contraceptive; Ophthalmic; Stomachic,None known
182,Sydney Peppermint,Eucalyptus piperita - Sm.,Stomachic,"Citronellal, an essential oil found in most Eucalyptus species is reported to be mutagenic when used in isolation[269]. In large doses, oil of eucalyptus, like so many essential oils has caused fatalities from intestinal irritation[269]. Death is reported from ingestion of 4 - 24 ml of essential oils, but recoveries are also reported for the same amount[269]. Symptoms include gastroenteric burning and irritation, nausea, vomiting, diarrhoea, oxygen deficiency, ,weakness, dizziness, stupor, difficult respiration, delirium, paralysis, convulsions, and death, usually due to respiratory failure[269]."
185,Thymeleaf Sandmat,Euphorbia serpyllifolia - Pers.,Dysentery; Galactogogue; Haemostatic; Odontalgic; Poultice; Skin; Stings; Stomachic; Warts,"The sap contains a latex which is toxic on ingestion and highly irritant externally, causing photosensitive skin reactions and severe inflammation, especially on contact with eyes or open cuts. The toxicity can remain high even in dried plant material[200]. Prolonged and regular contact with the sap is inadvisable because of its carcinogenic nature[214]."
188,"Fennel, Sweet fennel",Foeniculum vulgare - Mill.,Analgesic; Antiinflammatory; Antispasmodic; Aromatherapy; Aromatic; Carminative; Diuretic; Emmenagogue; Expectorant; Galactogogue; Hallucinogenic; Stimulant; Stomachic; Urinary,"Skin contact with the sap or essential oil is said to cause photo-sensitivity and/or dermatitis in some people[218, 222]. Ingestion of the oil can cause vomiting, seizures and pulmonary oedema[222]. Avoid for small children. Avoid if cirrhosis/liver disorders. Diabetics check sugar content of preparation [301]."
189,Florence Fennel,Foeniculum vulgare azoricum - (Mill.)Thell.,Analgesic; Antiinflammatory; Antispasmodic; Aromatic; Carminative; Diuretic; Emmenagogue; Expectorant; Galactogogue; Hallucinogenic; Stimulant; Stomachic; Urinary,"Skin contact with the sap or essential oil is said to cause photo-sensitivity and/or dermatitis in some people[218, 222]. Ingestion of the oil can cause vomiting, seizures and pulmonary oedema[222]."
190,Sweet Fennel,Foeniculum vulgare dulce - (Mill.)Batt.&Trab.,Analgesic; Antiinflammatory; Antispasmodic; Aromatic; Carminative; Diuretic; Emmenagogue; Expectorant; Galactogogue; Hallucinogenic; Stimulant; Stomachic; Urinary,"Skin contact with the sap or essential oil is said to cause photo-sensitivity and/or dermatitis in some people[218, 222]. Ingestion of the oil can cause vomiting, seizures and pulmonary oedema[222]."
220,"Butterfly Ginger, White garland-lily, Garland Flower, Butterfly Lily",Hedychium coronarium - J.König.,Antirheumatic; Aromatic; Carminative; Febrifuge; Stomachic; Tonic,None known
261,"English Lavender, True Lavender",Lavandula angustifolia - Mill.,Antianxiety; Antihalitosis; Antiseptic; Antispasmodic; Appetizer; Aromatherapy; Aromatic; Carminative; Cholagogue; Diuretic; Nervine; Sedative; Stimulant; Stomachic; Tonic,The volatile oil may rarely cause sensitization [301].
262,"Lavender, Lavandin",Lavandula x intermedia - Emeric. ex Loisel.,Antihalitosis; Antiseptic; Antispasmodic; Aromatherapy; Aromatic; Carminative; Cholagogue; Diuretic; Nervine; Sedative; Stimulant; Stomachic; Tonic,None known
265,"Wild Rosemary, Marsh Labrador tea",Ledum palustre - L.,Astringent; Diaphoretic; Diuretic; Homeopathy; Laxative; Narcotic; Stomachic,Plants contain a narcotic toxin called Ledel. This toxin only causes problems if the leaves are cooked for a long period in a closed container[172].
299,"Eau De Cologne Mint, Eau de Cologne Mint, Peppermint",Mentha x piperita citrata - (Ehrh.)Briq.,Anodyne; Antiseptic; Antispasmodic; Carminative; Cholagogue; Diaphoretic; Refrigerant; Stomachic; Tonic; Vasodilator,"Although no specific mention has been seen for this sub-species, it should be noted that, in large quantities, the closely allied M. x piperita vulgaris can cause abortions, especially when used in the form of the extracted essential oil, so it should not be used by pregnant women."
300,White Peppermint,Mentha x piperita officinalis - L.,Anodyne; Antiseptic; Antispasmodic; Aromatherapy; Carminative; Cholagogue; Diaphoretic; Refrigerant; Stomachic; Tonic; Vasodilator,"In large quantities this plant, especially in the form of the extracted essential oil, can cause abortions so should not be used by pregnant women."
301,Black Peppermint,Mentha x piperita vulgaris - L.,Abortifacient; Anodyne; Antiseptic; Antispasmodic; Aromatherapy; Carminative; Cholagogue; Diaphoretic; Refrigerant; Stomachic; Tonic; Vasodilator,"In large quantities this plant, especially in the form of the extracted essential oil, can cause abortions so should not be used by pregnant women."
403,Rosemary,Rosmarinus officinalis - L.,Antiseptic; Antispasmodic; Appetizer; Aromatherapy; Aromatic; Astringent; Cardiac; Carminative; Cholagogue; Diaphoretic; Emmenagogue; Nervine; Ophthalmic; Stimulant; Stomachic; Tonic,"Products containing rosemary oil may cause erythema (redness) of the skin. Caution needed if allergies. Reportedly used as an abortifacient in large quantities but can lead to deep coma, spasm and vomiting and even death [301]."
420,Purple Sage,Salvia carnosa - Douglas.,Analgesic; Antispasmodic; Febrifuge; Pectoral; Stomachic,None known
437,"Wild Potato, Fendler's horsenettle, Texan horsenettle",Solanum fendleri - A.Gray.,Stomachic,"Although no specific mention of toxicity has been seen for this species, it belongs to a genus where many if not all the members have poisonous leaves and sometimes also the unripe fruits."
442,California Hedgenettle,Stachys bullata - Benth.,Disinfectant; Poultice; Skin; Stomachic; Vulnerary,None known
452,Dandelion,Taraxacum officinale - Webb.,Aperient; Cholagogue; Depurative; Diuretic; Eczema; Hepatic; Hypoglycaemic; Laxative; Miscellany; Stomachic; Tonic; Urinary; Vitamin C; Warts,"This plant has been mentioned in various books on poisonous plants but any possible toxins will be of very low concentration and toxicity[10]. There are reports that some people have suffered dermatitis as a result of touching the plant, this is probably caused by the latex in the leaves and stems[222]."
454,Cat Thyme,Teucrium marum - L.,Aromatic; Astringent; Deobstruent; Diuretic; Nervine; Stimulant; Stomachic; Tonic,None known
504,Saigon Cinnamon,Cinnamomum loureiroi - Nees,Aromatic; Astringent; Carminative; Stimulant; Stomachic,None known
521,"Mondia, White's Ginger",Mondia whitei - (Hook.f.) Skeels,Antidepressant; Antiemetic; Antiinflammatory; Antitussive; Aphrodisiac; Appetizer; Carminative; Digestive; Diuretic; Expectorant; Laxative; Malaria; Parasiticide; Purgative; Restorative; Stomachic; Tonic; Urinary,The seeds are used as a substitute for Strophanthus seeds in the preparation of arrow poison[299 ]. The latex is also added to Strophanthus arrow poison[299 ].
540,"Spiral Ginger, Ginger lily, White spiral costus.",Costus afer - Ker Gawl.,Abortifacient; Anaesthetic; Anodyne; Antiarthritic; Antibacterial; Antibilious; Antidiarrhoeal; Antifungal; Antihaemorrhoidal; Antiinflammatory; Antirheumatic; Antispasmodic; Antitussive; Cancer; Cardiac; Cytotoxic; Diuretic; Diuretic; Dysentery; Epilepsy; Febrifuge; Hypoglycaemic; Hypotensive; Leprosy; Malaria; Ophthalmic; Parasiticide; Rubefacient; Skin; Stomachic,None known
595,White Dead Nettle,Lamium album - L.,Antiflatulent; Antispasmodic; Astringent; Cancer; Cholagogue; Depurative; Diuretic; Expectorant; Homeopathy; Hypnotic; Ophthalmic; Pectoral; Resolvent; Sedative; Styptic; Tonic; Vasoconstrictor; Vulnerary,None known
597,"Red Dead Nettle, Purple deadnettle",Lamium purpureum - L.,Astringent; Diaphoretic; Diuretic; Purgative; Styptic,None known
773,"Mayweed, Stinking chamomile",Anthemis cotula - L.,Antispasmodic; Astringent; Diaphoretic; Diuretic; Emetic; Emmenagogue; Epilepsy; Stings; Tonic,"The whole plant is penetrated by an acrid juice, touching or ingesting the plant can cause allergies in some people[4, 222]."
801,"Asarabacca, European Wild Ginger",Asarum europaeum - L.,Cathartic; Diaphoretic; Emetic; Errhine; Sternutatory; Stimulant; Tonic,"The plant is poisonous in large doses[13, 19], the toxin is neutralized by drying[7]."
820,"Chitra, Indian Barberry or Tree Turmeric",Berberis aristata - DC.,Alterative; Antibacterial; Antiperiodic; Bitter; Cancer; Deobstruent; Diaphoretic; Dysentery; Laxative; Malaria; Ophthalmic; Tonic; Vitamin C,None known
1009,"Maidenhair Tree, Ginkgo",Ginkgo biloba - L.,Antianxiety; Antiasthmatic; Antibacterial; Antifungal; Astringent; Cancer; Digestive; Expectorant; Infertility; Ophthalmic; Sedative; Tonic; Urinary; Vermifuge,"The seed contains a mildly acrimonious principle that is unstable when heated. It is therefore best to cook the seed before eating it to ensure any possible toxicity is destroyed. This acrimonious principle is probably 4'-methoxypyridoxine, which can destroy vitamin B6[237]. It is more toxic for children, but the raw nuts would have to be eaten often over a period of time for the negative effects to become apparent[237]. Avoid if known allergy to Ginkgo or cross-react species (cashew, poison ivy). Not recommended for children. Avoid if on blood thinning medication (e.g. warfarin). Discontinue prior to surgery. Avoid parenteral use as possible hypotension, shock, dizziness. Excessive seed ingestion can cause 'gin-man' food poisoning [301]."
1129,Lemon Balm,Melissa officinalis - L.,Antianxiety; Antibacterial; Antidepressant; Antiemetic; Antispasmodic; Antiviral; Aromatherapy; Carminative; Diaphoretic; Digestive; Emmenagogue; Febrifuge; Sedative; Tonic,Can cause irritation in high concentrates. Avoid during pregnancy. Care if sensitive skin [301].
1143,"Wax Myrtle - Bayberry Wild Cinnamon, Southern Bayberry, Wax Myrtle, Southern Wax Myrtle",Myrica cerifera - L.,Antibacterial; Astringent; Dysentery; Emetic; Narcotic; Sternutatory; Stimulant; Tonic,There is a report that some of the constituents of the wax are carcinogenic[222]. Vomiting in large doses. Constituent myricadiol may cause salt retention and potassium excretion [301]. Avoid if high blood pressure or kidney disease. Tannin constituents may cause gastrointestinal irritation and liver damage [301].
1302,"Greek Sage, Greek oregano",Salvia fruticosa - Mill.,Antihydrotic; Antiseptic; Antispasmodic; Astringent; Carminative; Cholagogue; Depurative; Expectorant; Febrifuge; Stimulant; Tonic; Vasodilator,None known
1303,Spanish Sage,Salvia lavandulifolia - Vahl.,Alterative; Antiseptic; Astringent; Depurative; Digestive; Expectorant; Febrifuge; Tonic,None known
1305,"Sage, Kitchen sage, Small Leaf Sage, Garden Sage",Salvia officinalis - L.,Antidiarrhoeal; Antihydrotic; Antiseptic; Antispasmodic; Appetizer; Aromatherapy; Astringent; Carminative; Cholagogue; Galactofuge; Stimulant; Tonic; Vasodilator,"The plant can be toxic when used in excess or when taken for extended periods[238] symptoms include: restlessness, vomiting, vertigo, tremors, seizures. Contraindicated during pregnancy. Avoid if predisposed to convulsions [301]."
1306,"Clary, Europe sage, Clary Sage",Salvia sclarea - L.,Antispasmodic; Appetizer; Aromatherapy; Aromatic; Astringent; Balsamic; Carminative; Ophthalmic; Pectoral; Tonic,None known
1313,Thyme-Leaved Savory,Satureja thymbra - L.,Antibacterial; Aromatic; Digestive; Expectorant; Tonic,None known
1343,"Wood Betony, Common hedgenettle, Betony, Woundwort",Stachys officinalis - (L.)Trevis.,Anthelmintic; Antiseptic; Astringent; Carminative; Cathartic; Cholagogue; Digestive; Diuretic; Emetic; Emmenagogue; Expectorant; Homeopathy; Nervine; Sedative; Sternutatory; Tonic; Vulnerary,None known
1344,"Marsh Woundwort, Marsh hedgenettle",Stachys palustris - L.,Antiseptic; Antispasmodic; Emetic; Emmenagogue; Expectorant; Haemostatic; Nervine; Sedative; Tonic; Vulnerary,Avoid during pregnancy & breast feeding [301].

### 3. Building a Tag Library

In [16]:
strandard_tags = [
    "stress",
    "sleep",
    "anxiety",
    "panic",
    "nervousness",
    "focus",
    "digestion",
    "pain",
    "inflammation",
    "immune_support",
    "respiratory_support",
    "heart_support",
    "circulation",
    "skin",
    "edema",
    "energy",
    "relaxation"
]

In [17]:
# First manual tagging for MVP dataset

mvp_data.loc[8, "user_need_tags"] = "digestion,stomach,pain"
mvp_data.loc[8, "effect_tags"] = "diuretic,odontalgic,rubefacient,stomachic"

mvp_data.loc[19, "user_need_tags"] = "pain,inflammation,digestion"
mvp_data.loc[19, "effect_tags"] = "analgesic,antirheumatic,stomachic"

mvp_data.loc[28, "user_need_tags"] = "digestion,immune_support,respiratory_support,cholesterol"
mvp_data.loc[28, "effect_tags"] = "anthelmintic,antiasthmatic,anticholesterolemic"

mvp_data.loc[29, "user_need_tags"] = "digestion,immune_support,respiratory_support,cholesterol"
mvp_data.loc[29, "effect_tags"] = "anthelmintic,antiasthmatic,anticholesterolemic"

mvp_data.loc[30, "user_need_tags"] = "digestion,heart_support,immune_support"
mvp_data.loc[30, "effect_tags"] = "antibacterial,cardiac,digestive,stomachic"

mvp_data.loc[31, "user_need_tags"] = "digestion,immune_support,respiratory_support,cholesterol"
mvp_data.loc[31, "effect_tags"] = "anthelmintic,antiasthmatic,anticholesterolemic"

mvp_data.loc[38, "user_need_tags"] = "skin,digestion,constipation"
mvp_data.loc[38, "effect_tags"] = "emollient,laxative,stomachic"

mvp_data.loc[63, "user_need_tags"] = "digestion,stomach"
mvp_data.loc[63, "effect_tags"] = "carminative,stomachic"

mvp_data.loc[64, "user_need_tags"] = "pain,skin,infection"
mvp_data.loc[64, "effect_tags"] = "antispasmodic,deodorant,disinfectant,poultice"

mvp_data.loc[72, "user_need_tags"] = "digestion,immune_support,respiratory_support"
mvp_data.loc[72, "effect_tags"] = "anthelmintic,antiasthmatic,antibiotic"

In [18]:
mvp_data.loc[[8, 19, 28, 29, 30, 31, 38, 63, 64, 72],
             ["Common Name", "Medicinal Properties", "user_need_tags", "effect_tags"]]

,Common Name,Medicinal Properties,user_need_tags,effect_tags
8,Basil Thyme,Diuretic; Odontalgic; Rubefacient; Stomachic,"digestion,stomach,pain","diuretic,odontalgic,rubefacient,stomachic"
19,"Giant Hyssop, Nettleleaf giant hyssop",Analgesic; Antirheumatic; Stomachic,"pain,inflammation,digestion","analgesic,antirheumatic,stomachic"
28,"Garlic, Cultivated garlic",Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Hypoglycaemic; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"digestion,immune_support,respiratory_support,cholesterol","anthelmintic,antiasthmatic,anticholesterolemic"
29,Serpent Garlic,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"digestion,immune_support,respiratory_support,cholesterol","anthelmintic,antiasthmatic,anticholesterolemic"
30,"Garlic Chives, Chinese chives, Oriental Chives,",Antibacterial; Cardiac; Digestive; Stomachic; Tonic; Urinary,"digestion,heart_support,immune_support","antibacterial,cardiac,digestive,stomachic"
31,Wild Garlic,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Astringent; Cholagogue; Depurative; Diaphoretic; Disinfectant; Diuretic; Expectorant; Febrifuge; Hypotensive; Rubefacient; Stimulant; Stomachic; Tonic; Vasodilator,"digestion,immune_support,respiratory_support,cholesterol","anthelmintic,antiasthmatic,anticholesterolemic"
38,"Aloe Vera, Barbados aloe, First Aid Plant, Medicinal Aloe",Cancer; Emmenagogue; Emollient; Laxative; Miscellany; Purgative; Skin; Stimulant; Stomachic; Tonic; Vermifuge; Vulnerary,"skin,digestion,constipation","emollient,laxative,stomachic"
63,"Sand Sage, Sand sagebrush",Carminative; Miscellany; Stomachic,"digestion,stomach","carminative,stomachic"
64,"Fringed Wormwood, Prairie sagewort",Antispasmodic; Deodorant; Disinfectant; Poultice; Stimulant; Stomachic; Vermifuge; Women's complaints,"pain,skin,infection","antispasmodic,deodorant,disinfectant,poultice"
72,"Snake Root, Canadian wildginger, Canada Wild Ginger, Wild Ginger",Anthelmintic; Antiasthmatic; Antibiotic; Antitumor; Carminative; Contraceptive; Diaphoretic; Diuretic; Expectorant; Irritant; Poultice; Salve; Stimulant; Stomachic; Tonic,"digestion,immune_support,respiratory_support","anthelmintic,antiasthmatic,antibiotic"

In [19]:
# Automatic first tagging based on Medicinal Properties

tag_rules = {
    "digestion": ["stomachic", "digestive", "carminative", "apperizer", "laxative"],
    "pain": ["analgesic", "anodyne", "odontalgic", "antirheumatic"],
    "inflammatory": ["antiinflammatory", "antiphlogistic"],
    "respiratory_support": ["antiasthmatic", "expectorant", "pectorale"],
    "immune_support": ["antibacterial", "antibiotic", "antifungal", "antiseptic", "antiviral"],
    "skin": ["emollient", "vulnerary", "poultice", "desinfectant", "rubefacient"],
    "stress": ["sedative", "nervine", "antidepressant", "antianxiety"],
    "sleep": ["sedative", "nervine"],
    "anxiety": ["antianxiety", "nervine", "sedative"],
    "relaxation": ["sedative", "nervine"],
    "heart_support": ["cardiac", "vasodilator", "hypotensive"],
    "circulation": ["vasodilator", "diaphoretic"],
    "edema": ["diuretic"],
    "energy": ["stimulant", "tonic"],
    "focus": ["stimulant", "tonic"]
}

def generate_user_tags(properties):
    if pd.isna(properties):
        return ""
    
    text = properties.lower()
    tags = []

    for user_tag, keywords in tag_rules.items():
        if any(keyword in text for keyword in keywords):
            tags.append(user_tag)
    
    return ",".join(sorted(set(tags)))


def clean_effect_tags(properties):
    if pd.isna(properties):
        return ""
    
    return properties.lower().replace("; ", ", ").replace(";", ",")


# Apply to MVP data
mvp_data["user_need_tags"] = mvp_data["Medicinal Properties"].apply(generate_user_tags)
mvp_data["effect_tags"] = mvp_data["Medicinal Properties"].apply(clean_effect_tags)

In [20]:
# Controlling all 50 data

mvp_data[[
    "Common Name",
    "Medicinal Properties",
    "user_need_tags",
    "effect_tags",
    "Known Hazards"
]].head(50)

,Common Name,Medicinal Properties,user_need_tags,effect_tags,Known Hazards
8,Basil Thyme,Diuretic; Odontalgic; Rubefacient; Stomachic,"digestion,edema,pain,skin","diuretic, odontalgic, rubefacient, stomachic",None known
19,"Giant Hyssop, Nettleleaf giant hyssop",Analgesic; Antirheumatic; Stomachic,"digestion,pain","analgesic, antirheumatic, stomachic",None known
28,"Garlic, Cultivated garlic",Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Hypoglycaemic; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"circulation,digestion,edema,energy,focus,heart_support,immune_support,respiratory_support","anthelmintic, antiasthmatic, anticholesterolemic, antiseptic, antispasmodic, cancer, cholagogue, diaphoretic, diuretic, dysentery, expectorant, febrifuge, hypoglycaemic, stimulant, stings, stomachic, tonic, vasodilator","There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]. Avoid with anticlotting medication. Breastfeeding may worsen baby's colic. Avoid several weeks prior to surgery. Bad breath!! [301]."
29,Serpent Garlic,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"circulation,digestion,edema,energy,focus,heart_support,immune_support,respiratory_support","anthelmintic, antiasthmatic, anticholesterolemic, antiseptic, antispasmodic, cancer, cholagogue, diaphoretic, diuretic, dysentery, expectorant, febrifuge, stimulant, stings, stomachic, tonic, vasodilator","There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]."
30,"Garlic Chives, Chinese chives, Oriental Chives,",Antibacterial; Cardiac; Digestive; Stomachic; Tonic; Urinary,"digestion,energy,focus,heart_support,immune_support","antibacterial, cardiac, digestive, stomachic, tonic, urinary","Although no individual reports regarding this species have been seen, there have been cases of poisoning caused by the consumption, in very large quantities and by some mammals, of certain members of this genus. Dogs seem to be particularly susceptible[76]."
31,Wild Garlic,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Astringent; Cholagogue; Depurative; Diaphoretic; Disinfectant; Diuretic; Expectorant; Febrifuge; Hypotensive; Rubefacient; Stimulant; Stomachic; Tonic; Vasodilator,"circulation,digestion,edema,energy,focus,heart_support,immune_support,respiratory_support,skin","anthelmintic, antiasthmatic, anticholesterolemic, antiseptic, antispasmodic, astringent, cholagogue, depurative, diaphoretic, disinfectant, diuretic, expectorant, febrifuge, hypotensive, rubefacient, stimulant, stomachic, tonic, vasodilator","There have been cases of poisoning caused by the consumption, in very large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]."
38,"Aloe Vera, Barbados aloe, First Aid Plant, Medicinal Aloe",Cancer; Emmenagogue; Emollient; Laxative; Miscellany; Purgative; Skin; Stimulant; Stomachic; Tonic; Vermifuge; Vulnerary,"digestion,energy,focus,skin","cancer, emmenagogue, emollient, laxative, miscellany, purgative, skin, stimulant, stomachic, tonic, vermifuge, vulnerary","Taken by mouth may cause cramping pain in the gastrointestinal tract and diarrhoea (reduce dose). Skin rashes with long term use of gel. Rare adverse effects are on heart rhythm, kidney damage and oedema. Long term use can cause electrolytes loss esp. potassium and may therefore enhance the effect of drugs that act on the heart (e.g. digoxin) [301]."
63,"Sand Sage, Sand sagebrush",Carminative; Miscellany; Stomachic,digestion,"carminative, miscellany, stomachic","Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]."
64,"Fringed Wormwood, Prairie sagewort",Antispasmodic; Deodorant; Disinfectant; Poultice; Stimulant; Stomachic; Vermifuge; Women's complaints,"digestion,energy,focus,skin","antispasmodic, deodorant, disinfectant, poultice, stimulant, stomachic, vermifuge, women's complaints","Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]."
72,"Snake Root, Canadian wildginger, Canada Wild Ginger, Wild Ginger",Anthelmintic; Antiasthmatic; Antibiotic; Antitumor; Carminative; Contraceptive; Diaphoretic; Diuretic; Expectorant; Irritant; Poultice; Salve; Stimulant; Stomachic; Tonic,"circulation,digestion,edema,energy,focus,immune_support,respiratory_support,skin","anthelmintic, antiasthmatic, antibiotic, antitumor, carminative, contraceptive, diaphoretic, diuretic, expectorant, irritant, poultice, salve, stimulant, stomachic, tonic",The leaves are poisonous[19]. Handling the leaves is said to cause dermatitis in some people[269].
73,"Wild Ginger, British Columbia wildginger",Analgesic; Antirheumatic; Appetizer; Laxative; Poultice; Stomachic; Tonic,"digestion,energy,focus,pain,skin","analgesic, antirheumatic, appetizer, laxative, poultice, stomachic, tonic","Although no reports of toxicity have been found for this plant, at least 3 other members of this genus have reports that the leaves are toxic[7, 19]. Some caution is therefore advised in the use of this plant."
112,"Nettle Tree, European hackberry",Astringent; Dysentery; Lenitive; Stomachic,digestion,"astringent, dysentery, lenitive, stomachic",None known
121,"Chamomile, Roman chamomile",Anodyne; Antianxiety; Antiinflammatory; Antispasmodic; Aromatherapy; Nervine; Stomachic; Tonic; Vasodilator,"anxiety,circulation,digestion,energy,focus,heart_support,inflammatory,pain,relaxation,sleep,stress","anodyne, antianxiety, antiinflammatory, antispasmodic, aromatherapy, nervine, stomachic, tonic, vasodilator","Patients with severe allergic responses to ragweed (ragwort) should be warned about the possible cross-sensitivity to chamomile and other members of the Asteraceae/Compositae family (e.g. echinacea, feverfew, milk thistle)."
177,"Antelope Sage, James' buckwheat",Analgesic; Cardiac; Contraceptive; Ophthalmic; Stomachic,"digestion,heart_support,pain","analgesic, cardiac, contraceptive, ophthalmic, stomachic",None known
182,Sydney Peppermint,Stomachic,digestion,stomachic,"Citronellal, an essential oil found in most Eucalyptus species is reported to be mutagenic when used in isolation[269]. In large doses, oil of eucalyptus, like so many essential oils has caused fatalities from intestinal irritation[269]. Death is reported from ingestion of 4 - 24 ml of essential oils, but recoveries are also reported for the same amount[269]. Symptoms include gastroenteric burning and irritation, nausea, vomiting, diarrhoea, oxygen deficiency, ,weakness, dizziness, stupor, difficult respiration, delirium, paralysis, convulsions, and death, usually due to respiratory failure[269]."
185,Thymeleaf Sandmat,Dysentery; Galactogogue; Haemostatic; Odontalgic; Poultice; Skin; Stings; Stomachic; Warts,"digestion,pain,skin","dysentery, galactogogue, haemostatic, odontalgic, poultice, skin, stings, stomachic, warts","The sap contains a latex which is toxic on ingestion and highly irritant externally, causing photosensitive skin reactions and severe inflammation, especially on contact with eyes or open cuts. The toxicity can remain high even in dried plant material[200]. Prolonged and regular contact with the sap is inadvisable because of its carcinogenic nature[214]."
188,"Fennel, Sweet fennel",Analgesic; Antiinflammatory; Antispasmodic; Aromatherapy; Aromatic; Carminative; Diuretic; Emmenagogue; Expectorant; Galactogogue; Hallucinogenic; Stimulant; Stomachic; Urinary,"digestion,edema,energy,focus,inflammatory,pain,respiratory_support","analgesic, antiinflammatory, antispasmodic, aromatherapy, aromatic, carminative, diuretic, emmenagogue, expectorant, galactogogue, hallucinogenic, stimulant, stomachic, urinary","Skin contact with the sap or essential oil is said to cause photo-sensitivity and/or dermatitis in some people[218, 222]. Ingestion of the oil can cause vomiting, seizures and pulmonary oedema[222]. Avoid for small children. Avoid if cirrhosis/liver disorders. Diabetics check sugar content of preparation [301]."
189,Florence Fennel,Analgesic; Antiinflammatory; Antispasmodic; Aromatic; Carminative; Diuretic; Emmenagogue; Expectorant; Galactogogue; Hallucinogenic; Stimulant; Stomachic; Urinary,"digestion,edema,energy,focus,inflammatory,pain,respiratory_support","analgesic, antiinflammatory, antispasmodic, aromatic, carminative, diuretic, emmenagogue, expectorant, galactogogue, hallucinogenic, stimulant, stomachic, urinary","Skin contact with the sap or essential oil is said to cause photo-sensitivity and/or dermatitis in some people[218, 222]. Ingestion of the oil can cause vomiting, seizures and pulmonary oedema[222]."
190,Sweet Fennel,Analgesic; Antiinflammatory; Antispasmodic; Aromatic; Carminative; Diuretic; Emmenagogue; Expectorant; Galactogogue; Hallucinogenic; Stimulant; Stomachic; Urinary,"digestion,edema,energy,focus,inflammatory,pain,respiratory_support","analgesic, antiinflammatory, antispasmodic, aromatic, carminative, diuretic, emmenagogue, expectorant, galactogogue, hallucinogenic, stimulant, stomachic, urinary","Skin contact with the sap or essential oil is said to cause photo-sensitivity and/or dermatitis in some people[218, 222]. Ingestion of the oil can cause vomiting, seizures and pulmonary oedema[222]."
220,"Butterfly Ginger, White garland-lily, Garland Flower, Butterfly Lily",Antirheumatic; Aromatic; Carminative; Febrifuge; Stomachic; Tonic,"digestion,energy,focus,pain","antirheumatic, aromatic, carminative, febrifuge, stomachic, tonic",None known
261,"English Lavender, True Lavender",Antianxiety; Antihalitosis; Antiseptic; Antispasmodic; Appetizer; Aromatherapy; Aromatic; Carminative; Cholagogue; Diuretic; Nervine; Sedative; Stimulant; Stomachic; Tonic,"anxiety,digestion,edema,energy,focus,immune_support,relaxation,sleep,stress","antianxiety, antihalitosis, antiseptic, antispasmodic, appetizer, aromatherapy, aromatic, carminative, cholagogue, diuretic, nervine, sedative, stimulant, stomachic, tonic",The volatile oil may rarely cause sensitization [301].
262,"Lavender, Lavandin",Antihalitosis; Antiseptic; Antispasmodic; Aromatherapy; Aromatic; Carminative; Cholagogue; Diuretic; Nervine; Sedative; Stimulant; Stomachic; Tonic,"anxiety,digestion,edema,energy,focus,immune_support,relaxation,sleep,stress","antihalitosis, antiseptic, antispasmodic, aromatherapy, aromatic, carminative, cholagogue, diuretic, nervine, sedative, stimulant, stomachic, tonic",None known
265,"Wild Rosemary, Marsh Labrador tea",Astringent; Diaphoretic; Diuretic; Homeopathy; Laxative; Narcotic; Stomachic,"circulation,digestion,edema","astringent, diaphoretic, diuretic, homeopathy, laxative, narcotic, stomachic",Plants contain a narcotic toxin called Ledel. This toxin only causes problems if the leaves are cooked for a long period in a closed container[172].
299,"Eau De Cologne Mint, Eau de Cologne Mint, Peppermint",Anodyne; Antiseptic; Antispasmodic; Carminative; Cholagogue; Diaphoretic; Refrigerant; Stomachic; Tonic; Vasodilator,"circulation,digestion,energy,focus,heart_support,immune_support,pain","anodyne, antiseptic, antispasmodic, carminative, cholagogue, diaphoretic, refrigerant, stomachic, tonic, vasodilator","Although no specific mention has been seen for this sub-species, it should be noted that, in large quantities, the closely allied M. x piperita vulgaris can cause abortions, especially when used in the form of the extracted essential oil, so it should not be used by pregnant women."
300,White Peppermint,Anodyne; Antiseptic; Antispasmodic; Aromatherapy; Carminative; Cholagogue; Diaphoretic; Refrigerant; Stomachic; Tonic; Vasodilator,"circulation,digestion,energy,focus,heart_support,immune_support,pain","anodyne, antiseptic, antispasmodic, aromatherapy, carminative, cholagogue, diaphoretic, refrigerant, stomachic, tonic, vasodilator","In large quantities this plant, especially in the form of the extracted essential oil, can cause abortions so should not be used by pregnant women."
301,Black Peppermint,Abortifacient; Anodyne; Antiseptic; Antispasmodic; Aromatherapy; Carminative; Cholagogue; Diaphoretic; Refrigerant; Stomachic; Tonic; Vasodilator,"circulation,digestion,energy,focus,heart_support,immune_support,pain","abortifacient, anodyne, antiseptic, antispasmodic, aromatherapy, carminative, cholagogue, diaphoretic, refrigerant, stomachic, tonic, vasodilator","In large quantities this plant, especially in the form of the extracted essential oil, can cause abortions so should not be used by pregnant women."
403,Rosemary,Antiseptic; Antispasmodic; Appetizer; Aromatherapy; Aromatic; Astringent; Cardiac; Carminative; Cholagogue; Diaphoretic; Emmenagogue; Nervine; Ophthalmic; Stimulant; Stomachic; Tonic,"anxiety,circulation,digestion,energy,focus,heart_support,immune_support,relaxation,sleep,stress","antiseptic, antispasmodic, appetizer, aromatherapy, aromatic, astringent, cardiac, carminative, cholagogue, diaphoretic, emmenagogue, nervine, ophthalmic, stimulant, stomachic, tonic","Products containing rosemary oil may cause erythema (redness) of the skin. Caution needed if allergies. Reportedly used as an abortifacient in large quantities but can lead to deep coma, spasm and vomiting and even death [301]."
420,Purple Sage,Analgesic; Antispasmodic; Febrifuge; Pectoral; Stomachic,"digestion,pain","analgesic, antispasmodic, febrifuge, pectoral, stomachic",None known
437,"Wild Potato, Fendler's horsenettle, Texan horsenettle",Stomachic,digestion,stomachic,"Although no specific mention of toxicity has been seen for this species, it belongs to a genus where many if not all the members have poisonous leaves and sometimes also the unripe fruits."
442,California Hedgenettle,Disinfectant; Poultice; Skin; Stomachic; Vulnerary,"digestion,skin","disinfectant, poultice, skin, stomachic, vulnerary",None known
452,Dandelion,Aperient; Cholagogue; Depurative; Diuretic; Eczema; Hepatic; Hypoglycaemic; Laxative; Miscellany; Stomachic; Tonic; Urinary; Vitamin C; Warts,"digestion,edema,energy,focus","aperient, cholagogue, depurative, diuretic, eczema, hepatic, hypoglycaemic, laxative, miscellany, stomachic, tonic, urinary, vitamin c, warts","This plant has been mentioned in various books on poisonous plants but any possible toxins will be of very low concentration and toxicity[10]. There are reports that some people have suffered dermatitis as a result of touching the plant, this is probably caused by the latex in the leaves and stems[222]."
454,Cat Thyme,Aromatic; Astringent; Deobstruent; Diuretic; Nervine; Stimulant; Stomachic; Tonic,"anxiety,digestion,edema,energy,focus,relaxation,sleep,stress","aromatic, astringent, deobstruent, diuretic, nervine, stimulant, stomachic, tonic",None known
504,Saigon Cinnamon,Aromatic; Astringent; Carminative; Stimulant; Stomachic,"digestion,energy,focus","aromatic, astringent, carminative, stimulant, stomachic",None known
521,"Mondia, White's Ginger",Antidepressant; Antiemetic; Antiinflammatory; Antitussive; Aphrodisiac; Appetizer; Carminative; Digestive; Diuretic; Expectorant; Laxative; Malaria; Parasiticide; Purgative; Restorative; Stomachic; Tonic; Urinary,"digestion,edema,energy,focus,inflammatory,respiratory_support,stress","antidepressant, antiemetic, antiinflammatory, antitussive, aphrodisiac, appetizer, carminative, digestive, diuretic, expectorant, laxative, malaria, parasiticide, purgative, restorative, stomachic, tonic, urinary",The seeds are used as a substitute for Strophanthus seeds in the preparation of arrow poison[299 ]. The latex is also added to Strophanthus arrow poison[299 ].
540,"Spiral Ginger, Ginger lily, White spiral costus.",Abortifacient; Anaesthetic; Anodyne; Antiarthritic; Antibacterial; Antibilious; Antidiarrhoeal; Antifungal; Antihaemorrhoidal; Antiinflammatory; Antirheumatic; Antispasmodic; Antitussive; Cancer; Cardiac; Cytotoxic; Diuretic; Diuretic; Dysentery; Epilepsy; Febrifuge; Hypoglycaemic; Hypotensive; Leprosy; Malaria; Ophthalmic; Parasiticide; Rubefacient; Skin; Stomachic,"digestion,edema,heart_support,immune_support,inflammatory,pain,skin","abortifacient, anaesthetic, anodyne, antiarthritic, antibacterial, antibilious, antidiarrhoeal, antifungal, antihaemorrhoidal, antiinflammatory, antirheumatic, antispasmodic, antitussive, cancer, cardiac, cytotoxic, diuretic, diuretic, dysentery, epilepsy, febrifuge, hypoglycaemic, hypotensive, leprosy, malaria, ophthalmic, parasiticide, rubefacient, skin, stomachic",None known
595,White Dead Nettle,Antiflatulent; Antispasmodic; Astringent; Cancer; Cholagogue; Depurative; Diuretic; Expectorant; Homeopathy; Hypnotic; Ophthalmic; Pectoral; Resolvent; Sedative; Styptic; Tonic; Vasoconstrictor; Vulnerary,"anxiety,edema,energy,focus,relaxation,respiratory_support,skin,sleep,stress","antiflatulent, antispasmodic, astringent, cancer, cholagogue, depurative, diuretic, expectorant, homeopathy, hypnotic, ophthalmic, pectoral, resolvent, sedative, styptic, tonic, vasoconstrictor, vulnerary",None known
597,"Red Dead Nettle, Purple deadnettle",Astringent; Diaphoretic; Diuretic; Purgative; Styptic,"circulation,edema","astringent, diaphoretic, diuretic, purgative, styptic",None known
773,"Mayweed, Stinking chamomile",Antispasmodic; Astringent; Diaphoretic; Diuretic; Emetic; Emmenagogue; Epilepsy; Stings; Tonic,"circulation,edema,energy,focus","antispasmodic, astringent, diaphoretic, diuretic, emetic, emmenagogue, epilepsy, stings, tonic","The whole plant is penetrated by an acrid juice, touching or ingesting the plant can cause allergies in some people[4, 222]."
801,"Asarabacca, European Wild Ginger",Cathartic; Diaphoretic; Emetic; Errhine; Sternutatory; Stimulant; Tonic,"circulation,energy,focus","cathartic, diaphoretic, emetic, errhine, sternutatory, stimulant, tonic","The plant is poisonous in large doses[13, 19], the toxin is neutralized by drying[7]."
820,"Chitra, Indian Barberry or Tree Turmeric",Alterative; Antibacterial; Antiperiodic; Bitter; Cancer; Deobstruent; Diaphoretic; Dysentery; Laxative; Malaria; Ophthalmic; Tonic; Vitamin C,"circulation,digestion,energy,focus,immune_support","alterative, antibacterial, antiperiodic, bitter, cancer, deobstruent, diaphoretic, dysentery, laxative, malaria, ophthalmic, tonic, vitamin c",None known
1009,"Maidenhair Tree, Ginkgo",Antianxiety; Antiasthmatic; Antibacterial; Antifungal; Astringent; Cancer; Digestive; Expectorant; Infertility; Ophthalmic; Sedative; Tonic; Urinary; Vermifuge,"anxiety,digestion,energy,focus,immune_support,relaxation,respiratory_support,sleep,stress","antianxiety, antiasthmatic, antibacterial, antifungal, astringent, cancer, digestive, expectorant, infertility, ophthalmic, sedative, tonic, urinary, vermifuge","The seed contains a mildly acrimonious principle that is unstable when heated. It is therefore best to cook the seed before eating it to ensure any possible toxicity is destroyed. This acrimonious principle is probably 4'-methoxypyridoxine, which can destroy vitamin B6[237]. It is more toxic for children, but the raw nuts would have to be eaten often over a period of time for the negative effects to become apparent[237]. Avoid if known allergy to Ginkgo or cross-react species (cashew, poison ivy). Not recommended for children. Avoid if on blood thinning medication (e.g. warfarin). Discontinue prior to surgery. Avoid parenteral use as possible hypotension, shock, dizziness. Excessive seed ingestion can cause 'gin-man' food poisoning [301]."

In [21]:
# Clean base dataset: Only rows with name and medicinal properties
clean_data = filtered_data.dropna(subset=["Common Name", "Medicinal Properties"]).copy()

# Reset index for clean slicing
clean_data = clean_data.reset_index(drop=True)

clean_data.shape

(12700, 20)

In [22]:
final_columns = [
    "Common Name",
    "Scientific Name",
    "Medicinal Properties",
    "Known Hazards",
    "Summary",
    "user_need_tags",
    "effect_tags",
    "preparation_type",
    "warning_level",
    "recommendation_reason"
]

#

## 4. Batch 1: 50 Plants

In [23]:
batch_1 = clean_data.iloc[0:50].copy()

batch_1["user_need_tags"] = batch_1["Medicinal Properties"].apply(generate_user_tags)
batch_1["effect_tags"] = batch_1["Medicinal Properties"].apply(clean_effect_tags)

batch_1["preparation_type"] = " "
batch_1["warning_level"] = " "
batch_1["recommendation_reason"] = " "

batch_1_final = batch_1[final_columns].copy()

batch_1_final.shape

(50, 10)

In [24]:
batch_1_final.head(4)

,Common Name,Scientific Name,Medicinal Properties,Known Hazards,Summary,user_need_tags,effect_tags,preparation_type,warning_level,recommendation_reason
0,"Musk Mallow,Musk Okra",Abelmoschus moschatus - Medik.,Antihalitosis; Antispasmodic; Aphrodisiac; Appetizer; Aromatherapy; Digestive; Nervine; Stomachic; Vulnerary,None known,NaN,"anxiety,digestion,relaxation,skin,sleep,stress","antihalitosis, antispasmodic, aphrodisiac, appetizer, aromatherapy, digestive, nervine, stomachic, vulnerary",,,
1,"Grand Fir, Giant Fir, Lowland White Fir",Abies grandis - (Douglas. ex D.Don.)Lindl.,Antirheumatic; Laxative; Ophthalmic; Skin; Stomachic; TB; Tonic,None known,"Form: Columnar, Upright or erect.","digestion,energy,focus,pain","antirheumatic, laxative, ophthalmic, skin, stomachic, tb, tonic",,,
2,Himalayan Fir,Abies spectabilis - (D.Don.)Spach.,Antiperiodic; Astringent; Carminative; Expectorant; Stomachic; Tonic,None known,NaN,"digestion,energy,focus,respiratory_support","antiperiodic, astringent, carminative, expectorant, stomachic, tonic",,,
3,"China Jute, Velvetleaf, Butterprint Buttonweed Jute, China Mallow, Indian Velvet Leaf",Abutilon theophrasti - Medik.,Astringent; Demulcent; Diuretic; Dysentery; Emollient; Laxative; Ophthalmic; Poultice; Stomachic; Urinary,None known,Form: Upright or erect.,"digestion,edema,skin","astringent, demulcent, diuretic, dysentery, emollient, laxative, ophthalmic, poultice, stomachic, urinary",,,

In [25]:
batch_1_final.to_csv("../data/processed/mvp_herbal_batch_01.csv", index=False)

## Batch 2: Next 50 Plants

In [26]:
batch_2 = clean_data.iloc[50:100].copy()

batch_2["user_need_tags"] = batch_2["Medicinal Properties"].apply(generate_user_tags)
batch_2["effect_tags"] = batch_2["Medicinal Properties"].apply(clean_effect_tags)

batch_2["preparation_type"] = " "
batch_2["warning_level"] = " "
batch_2["recommendation_reason"] = " "

batch_2_final = batch_2[final_columns].copy()

batch_2_final.shape

(50, 10)

In [27]:
batch_2_final.head(3)

,Common Name,Scientific Name,Medicinal Properties,Known Hazards,Summary,user_need_tags,effect_tags,preparation_type,warning_level,recommendation_reason
50,Southernwood,Artemisia abrotanum - L.,Anthelmintic; Antiseptic; Cholagogue; Deobstruent; Emmenagogue; Stomachic; Tonic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]. Safety during pregnancy is not known.",NaN,"digestion,energy,focus,immune_support","anthelmintic, antiseptic, cholagogue, deobstruent, emmenagogue, stomachic, tonic",,,
51,Field Southernwood,Artemisia campestris - L.,Abortifacient; Anthelmintic; Antiseptic; Cholagogue; Deobstruent; Eczema; Emmenagogue; Ophthalmic; Poultice; Stomachic; Tonic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222].","Common names include field wormwood, beach wormwood, northern wormwood, Breckland wormwood, boreal wormwood, Canadian wormwood, field sagewort and field mugwort.","digestion,energy,focus,immune_support,skin","abortifacient, anthelmintic, antiseptic, cholagogue, deobstruent, eczema, emmenagogue, ophthalmic, poultice, stomachic, tonic",,,
52,"Russian Tarragon, Tarragon, French Tarragon",Artemisia dracunculoides - Pursh.,Antiscorbutic; Diuretic; Emmenagogue; Hypnotic; Stomachic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222].","Bloom Color: Yellow. Main Bloom Time: Late summer, Mid summer. Form: Upright or erect.","digestion,edema","antiscorbutic, diuretic, emmenagogue, hypnotic, stomachic",,,

In [28]:
batch_2_final.to_csv("../data/processed/mvp_herbal_batch_02.csv", index=False)

## Batch 3

In [29]:
batch_3 = clean_data.iloc[50:100].copy()

batch_3["user_need_tags"] = batch_3["Medicinal Properties"].apply(generate_user_tags)
batch_3["effect_tags"] = batch_3["Medicinal Properties"].apply(clean_effect_tags)

batch_3["preparation_type"] = " "
batch_3["warning_level"] = " "
batch_3["recommendation_reason"] = " "

batch_3_final = batch_3[final_columns].copy()

batch_3_final.shape

(50, 10)

In [30]:
batch_3_final.head(3)

,Common Name,Scientific Name,Medicinal Properties,Known Hazards,Summary,user_need_tags,effect_tags,preparation_type,warning_level,recommendation_reason
50,Southernwood,Artemisia abrotanum - L.,Anthelmintic; Antiseptic; Cholagogue; Deobstruent; Emmenagogue; Stomachic; Tonic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]. Safety during pregnancy is not known.",NaN,"digestion,energy,focus,immune_support","anthelmintic, antiseptic, cholagogue, deobstruent, emmenagogue, stomachic, tonic",,,
51,Field Southernwood,Artemisia campestris - L.,Abortifacient; Anthelmintic; Antiseptic; Cholagogue; Deobstruent; Eczema; Emmenagogue; Ophthalmic; Poultice; Stomachic; Tonic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222].","Common names include field wormwood, beach wormwood, northern wormwood, Breckland wormwood, boreal wormwood, Canadian wormwood, field sagewort and field mugwort.","digestion,energy,focus,immune_support,skin","abortifacient, anthelmintic, antiseptic, cholagogue, deobstruent, eczema, emmenagogue, ophthalmic, poultice, stomachic, tonic",,,
52,"Russian Tarragon, Tarragon, French Tarragon",Artemisia dracunculoides - Pursh.,Antiscorbutic; Diuretic; Emmenagogue; Hypnotic; Stomachic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222].","Bloom Color: Yellow. Main Bloom Time: Late summer, Mid summer. Form: Upright or erect.","digestion,edema","antiscorbutic, diuretic, emmenagogue, hypnotic, stomachic",,,

In [31]:
batch_3_final.to_csv("../data/processed/mvp_herbal_batch_03.csv", index=False)

## Batch 4

In [32]:
batch_4 = clean_data.iloc[50:100].copy()

batch_4["user_need_tags"] = batch_4["Medicinal Properties"].apply(generate_user_tags)
batch_4["effect_tags"] = batch_4["Medicinal Properties"].apply(clean_effect_tags)

batch_4["preparation_type"] = " "
batch_4["warning_level"] = " "
batch_4["recommendation_reason"] = " "

batch_4_final = batch_4[final_columns].copy()

batch_4_final.shape

(50, 10)

In [33]:
batch_4_final.head(3)

,Common Name,Scientific Name,Medicinal Properties,Known Hazards,Summary,user_need_tags,effect_tags,preparation_type,warning_level,recommendation_reason
50,Southernwood,Artemisia abrotanum - L.,Anthelmintic; Antiseptic; Cholagogue; Deobstruent; Emmenagogue; Stomachic; Tonic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222]. Safety during pregnancy is not known.",NaN,"digestion,energy,focus,immune_support","anthelmintic, antiseptic, cholagogue, deobstruent, emmenagogue, stomachic, tonic",,,
51,Field Southernwood,Artemisia campestris - L.,Abortifacient; Anthelmintic; Antiseptic; Cholagogue; Deobstruent; Eczema; Emmenagogue; Ophthalmic; Poultice; Stomachic; Tonic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222].","Common names include field wormwood, beach wormwood, northern wormwood, Breckland wormwood, boreal wormwood, Canadian wormwood, field sagewort and field mugwort.","digestion,energy,focus,immune_support,skin","abortifacient, anthelmintic, antiseptic, cholagogue, deobstruent, eczema, emmenagogue, ophthalmic, poultice, stomachic, tonic",,,
52,"Russian Tarragon, Tarragon, French Tarragon",Artemisia dracunculoides - Pursh.,Antiscorbutic; Diuretic; Emmenagogue; Hypnotic; Stomachic,"Although no reports of toxicity have been seen for this species, skin contact with some members of this genus can cause dermatitis or other allergic reactions in some people[222].","Bloom Color: Yellow. Main Bloom Time: Late summer, Mid summer. Form: Upright or erect.","digestion,edema","antiscorbutic, diuretic, emmenagogue, hypnotic, stomachic",,,

In [34]:
batch_4_final.to_csv("../data/processed/mvp_herbal_batch_04.csv", index=False)

In [35]:
# Concatinating all 4 batches in 1 single dataset
mvp_dataset_base = pd.concat(
    [batch_1_final, batch_2_final, batch_3_final, batch_4_final],
    ignore_index=True
)

mvp_dataset_base.shape

(200, 10)

In [36]:
# 1. Add common plant into dataset
common_plants = [
    "chamomile", "lavender", "peppermint", "lemon balm", "ginger",
    "turmeric", "sage", "rosemary", "eucalyptus", "aloe",
    "valerian", "st john", "nettle", "fennel", "thyme",
    "garlic", "cinnamon", "dandelion", "passionflower", "ginko"
]

In [37]:
# 2. Searching for them in clean data
common_plants_data = clean_data[
    clean_data["Common Name"].str.lower().str.contains(
        "|".join(common_plants),
        na=False
    )
].copy()

common_plants_data.shape

(652, 20)

In [38]:
# 3. Apply tags + select final columns
common_plants_data["user_need_tags"] = common_plants_data["Medicinal Properties"].apply(generate_user_tags)
common_plants_data["effect_tags"] = common_plants_data["Medicinal Properties"].apply(clean_effect_tags)

common_plants_data["preparation_type"] = " "
common_plants_data["warning_level"] = " "
common_plants_data["recommendation_reason"] = " "

common_plants_final = common_plants_data[final_columns].copy()

common_plants_final.shape

(652, 10)

In [39]:
# Concat with 200 plants and remove dublicates
mvp_dataset = pd.concat(
    [mvp_dataset_base, common_plants_final],
    ignore_index=True
)

mvp_dataset = mvp_dataset.drop_duplicates(
    subset=["Common Name", "Scientific Name"]
).reset_index(drop=True)

mvp_dataset.shape

(242, 10)

In [40]:
mvp_dataset.to_csv("../data/processed/mvp_herbal_dataset.csv", index=False)

In [41]:
mvp_dataset.head()

,Common Name,Scientific Name,Medicinal Properties,Known Hazards,Summary,user_need_tags,effect_tags,preparation_type,warning_level,recommendation_reason
0,"Musk Mallow,Musk Okra",Abelmoschus moschatus - Medik.,Antihalitosis; Antispasmodic; Aphrodisiac; Appetizer; Aromatherapy; Digestive; Nervine; Stomachic; Vulnerary,None known,NaN,"anxiety,digestion,relaxation,skin,sleep,stress","antihalitosis, antispasmodic, aphrodisiac, appetizer, aromatherapy, digestive, nervine, stomachic, vulnerary",,,
1,"Grand Fir, Giant Fir, Lowland White Fir",Abies grandis - (Douglas. ex D.Don.)Lindl.,Antirheumatic; Laxative; Ophthalmic; Skin; Stomachic; TB; Tonic,None known,"Form: Columnar, Upright or erect.","digestion,energy,focus,pain","antirheumatic, laxative, ophthalmic, skin, stomachic, tb, tonic",,,
2,Himalayan Fir,Abies spectabilis - (D.Don.)Spach.,Antiperiodic; Astringent; Carminative; Expectorant; Stomachic; Tonic,None known,NaN,"digestion,energy,focus,respiratory_support","antiperiodic, astringent, carminative, expectorant, stomachic, tonic",,,
3,"China Jute, Velvetleaf, Butterprint Buttonweed Jute, China Mallow, Indian Velvet Leaf",Abutilon theophrasti - Medik.,Astringent; Demulcent; Diuretic; Dysentery; Emollient; Laxative; Ophthalmic; Poultice; Stomachic; Urinary,None known,Form: Upright or erect.,"digestion,edema,skin","astringent, demulcent, diuretic, dysentery, emollient, laxative, ophthalmic, poultice, stomachic, urinary",,,
4,"Sweet Acacia, Perfume Acacia, Huisache",Acacia farnesiana - (L.)Willd.,Astringent; Demulcent; Dysentery; Poultice; Stomachic,"The seeds, containing an unnamed alkaloid, are used to kill rabid dogs in Brazil[269].","Bloom Color: Yellow. Main Bloom Time: Early summer, Early fall, Early spring, Early winter, Late summer, Late fall, Late spring, Late winter, Mid summer, Mid fall, Mid spring, Mid winter. Form: Rounded, Spreading or horizontal, Vase.","digestion,skin","astringent, demulcent, dysentery, poultice, stomachic",,,

In [42]:
mvp_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Common Name            242 non-null    str
 1   Scientific Name        242 non-null    str
 2   Medicinal Properties   242 non-null    str
 3   Known Hazards          242 non-null    str
 4   Summary                108 non-null    str
 5   user_need_tags         242 non-null    str
 6   effect_tags            242 non-null    str
 7   preparation_type       242 non-null    str
 8   warning_level          242 non-null    str
 9   recommendation_reason  242 non-null    str
dtypes: str(10)
memory usage: 182.4 KB

## 5. Adding: Warning Level

In [43]:
def assign_warning_level(hazard):
    if pd.isna(hazard) or hazard.lower() == "none known":
        return "low"
    
    text = hazard.lower()

    high_keywords = ["poisonous", "toxic", "pregnant", "abortion", "death", "convulsions"]
    medium_keywords = ["allergic", "irritation", "dermatitis", "sensitization", "caution"]

    if any(word in text for word in high_keywords):
        return "high"
    elif any(word in text for word in medium_keywords):
        return "medium"
    else:
        return "medium"
    
mvp_dataset["warning_level"] = mvp_dataset["Known Hazards"].apply(assign_warning_level)

In [44]:
mvp_dataset["warning_level"].value_counts()

warning_level
low       109
high       69
medium     64
Name: count, dtype: int64

In [45]:
mvp_dataset.head(3)

,Common Name,Scientific Name,Medicinal Properties,Known Hazards,Summary,user_need_tags,effect_tags,preparation_type,warning_level,recommendation_reason
0,"Musk Mallow,Musk Okra",Abelmoschus moschatus - Medik.,Antihalitosis; Antispasmodic; Aphrodisiac; Appetizer; Aromatherapy; Digestive; Nervine; Stomachic; Vulnerary,None known,NaN,"anxiety,digestion,relaxation,skin,sleep,stress","antihalitosis, antispasmodic, aphrodisiac, appetizer, aromatherapy, digestive, nervine, stomachic, vulnerary",,low,
1,"Grand Fir, Giant Fir, Lowland White Fir",Abies grandis - (Douglas. ex D.Don.)Lindl.,Antirheumatic; Laxative; Ophthalmic; Skin; Stomachic; TB; Tonic,None known,"Form: Columnar, Upright or erect.","digestion,energy,focus,pain","antirheumatic, laxative, ophthalmic, skin, stomachic, tb, tonic",,low,
2,Himalayan Fir,Abies spectabilis - (D.Don.)Spach.,Antiperiodic; Astringent; Carminative; Expectorant; Stomachic; Tonic,None known,NaN,"digestion,energy,focus,respiratory_support","antiperiodic, astringent, carminative, expectorant, stomachic, tonic",,low,

In [46]:
mvp_dataset.to_csv("../data/processed/mvp_herbal_dataset_v2.csv", index=False)

## 6. Adding: Preparation Type

In [47]:
# def assign_preparation_type(row):
#     text = " ".join([
#         str(row.get("Medicinal Properties", "")),
#         str(row.get("Summary", "")),
#         str(row.get("Known Hazards", ""))
#     ]).lower()

#     preparation_types = []

#     if any(word in text for word in ["tea", "infusion", "decoction"]):
#         preparation_types.append("tea")

#     if any(word in text for word in ["oil", "essential oil"]):
#         preparation_types.append("oil")

#     if any(word in text for word in ["poultice", "compress"]):
#         preparation_types.append("poultice")

#     if any(word in text for word in ["tincture", "extract"]):
#         preparation_types.append("extract")

#     if any(word in text for word in ["capsule", "powder"]):
#         preparation_types.append("capsule_or_powder")

#     if any(word in text for word in ["juice", "gel"]):
#         preparation_types.append("juice_or_gel")

#     if not preparation_types:
#         return "unknown"
    
#     return ",".join(sorted(set(preparation_types)))

In [48]:
# mvp_dataset["preparation_type"] = mvp_dataset.apply(
#     assign_preparation_type,
#     axis=1
# )

In [49]:
# mvp_dataset[
#     ["Common Name", "preparation_type"]
# ].head(20)

In [50]:
danger_keywords = [
    "poisonous",
    "toxic",
    "should not be used",
    "avoid",
    "death",
    "convulsions",
    "abortion",
    "pregnant",
    "pragnancy",
    "breastfeeding"
    "contraindicated",
    "cardiogenic",
    "highly irritant",
    "narcotic"
    "kidney",
    "liver",
    "blood pressure",
    "heart",
    "medication",
    "interaction",
    "large doses",
    "overdose",
    "vomitting",
    "seizures"
]

def has_high_risk_warning(row):
    hazard_text = str(row.get("Known Hazards", "")).lower()
    return any(keyword in hazard_text for keyword in danger_keywords)

In [51]:
# Improved preparation type assignment
preparation_rules = {
    "tea": ["tea", "infusion", "decoction", "herbal tea"],
    "oil": ["oil", "essential oil", "aromatherapy"],
    "topical": ["topical", "skin", "wound", "burn", "external", "externally"],
    "cream_or_onitment": ["cream", "onitment", "salve", "balm", "lotion"],
    "poultice": ["compress", "plaster"],
    "extract": ["extract", "tincture", "essence"],
    "capsule_or_powder": ["capsule", "powder", "dried", "ground"],
    "juice_or_gel": ["juice", "gel", "sap"],
    "food": ["edible", "eaten", "culinary", "spice", "flavouring", "salad"],
    "smoke_or_incense": ["smoke", "smoking", "incense", "fumigation", "burned", "burnt"]
}

In [52]:
def assign_preparation_type(row):
    # safety override first
    if has_high_risk_warning(row):
        return "not recommended due to safety concerns"
    
    text = " ".join([
        str(row.get("Medicinal Properties", "")),
        str(row.get("Summary", "")),
        str(row.get("Known Hazards", "")),
        str(row.get("effect_tags", "")),
        str(row.get("user_need_tags", ""))
    ]).lower()

    found_types = []

    for prep_type, keywords in preparation_rules.items():
        if any(keyword in text for keyword in keywords):
            found_types.append(prep_type)

    if not found_types:
        return "unknown"
    
    return ",".join(sorted(set(found_types)))

In [53]:
mvp_dataset["preparation_type"] = mvp_dataset.apply(
    assign_preparation_type,
    axis=1
)

In [54]:
# Controlling it
mvp_dataset["preparation_type"].value_counts()

preparation_type
not recommended due to safety concerns                              84
unknown                                                             73
topical                                                             41
food,oil,topical                                                     4
food,oil                                                             4
capsule_or_powder                                                    4
oil                                                                  4
food                                                                 3
cream_or_onitment                                                    3
food,topical                                                         3
capsule_or_powder,topical                                            2
food,tea                                                             2
capsule_or_powder,food                                               2
oil,tea                                                              2
oil,topical                                                          1
cream_or_onitment,topical                                            1
capsule_or_powder,cream_or_onitment,extract,food,oil,tea,topical     1
capsule_or_powder,food,oil                                           1
food,juice_or_gel                                                    1
food,tea,topical                                                     1
capsule_or_powder,extract,food,oil                                   1
tea                                                                  1
juice_or_gel,topical                                                 1
poultice                                                             1
capsule_or_powder,food,oil,tea                                       1
Name: count, dtype: int64

In [55]:
mvp_dataset[
    ["Common Name", "Medicinal Properties", "Known Hazards", "preparation_type", "warning_level"]
].head(30)

,Common Name,Medicinal Properties,Known Hazards,preparation_type,warning_level
0,"Musk Mallow,Musk Okra",Antihalitosis; Antispasmodic; Aphrodisiac; Appetizer; Aromatherapy; Digestive; Nervine; Stomachic; Vulnerary,None known,"oil,topical",low
1,"Grand Fir, Giant Fir, Lowland White Fir",Antirheumatic; Laxative; Ophthalmic; Skin; Stomachic; TB; Tonic,None known,topical,low
2,Himalayan Fir,Antiperiodic; Astringent; Carminative; Expectorant; Stomachic; Tonic,None known,unknown,low
3,"China Jute, Velvetleaf, Butterprint Buttonweed Jute, China Mallow, Indian Velvet Leaf",Astringent; Demulcent; Diuretic; Dysentery; Emollient; Laxative; Ophthalmic; Poultice; Stomachic; Urinary,None known,topical,low
4,"Sweet Acacia, Perfume Acacia, Huisache",Astringent; Demulcent; Dysentery; Poultice; Stomachic,"The seeds, containing an unnamed alkaloid, are used to kill rabid dogs in Brazil[269].",topical,medium
5,Musk Milfoil,Appetizer; Diaphoretic; Digestive; Diuretic; Stomachic; Tonic,None known,unknown,low
6,Siberian Yarrow,Antibacterial; Antiinflammatory; Carminative; Diaphoretic; Emmenagogue; Odontalgic; Stomachic; Tonic,None known,unknown,low
7,Basil Thyme,Diuretic; Odontalgic; Rubefacient; Stomachic,None known,topical,low
8,Sweet Flag - Calamus,Abortifacient; Anodyne; Antirheumatic; Aphrodisiac; Aromatic; Carminative; Diaphoretic; Emmenagogue; Epilepsy; Febrifuge; Hallucinogenic; Homeopathy; Odontalgic; Sedative; Stimulant; Stomachic; Tonic; Vermifuge,"The fresh root can be poisonous[7]. When using the plant medicinally, the isolated essential oil should not be used[165]. The essential oil in the roots of some populations of this plant contains the compound asarone. This has tranquillising and antibiotic activity, but is also potentially toxic and carcinogenic[218, 238]. It seems that these compounds are found in the triploid form of the species (found in Asia) whilst the diploid form (found in N. America and Siberia) is free of the compounds[218, 238]. However, the root (but not the isolated essential oil) has been used in India for thousands of years without reports of cancer which suggests that using the whole herb is completely safe, though more research is needed[254]. Only roots free from or with a low content of beta asarone should be used in human herb therapy. Should be avoided in patients taking monoamine oxidase inhibitor antidepressants as possible side-effects [301].",not recommended due to safety concerns,high
9,"Grass-leaved Sweet Rush, Japanese Sweet Flag, Dwarf Sweet Flag",Anodyne; Antibacterial; Antifungal; Antiperiodic; Antirheumatic; Antispasmodic; Aromatic; Cardiac; Carminative; Diaphoretic; Diuretic; Emmenagogue; Epilepsy; Expectorant; Febrifuge; Parasiticide; Sedative; Stimulant; Stomachic; Tonic; Vermifuge,"Although no records of toxicity have been seen, this species belongs to a family where most of the species are poisonous, at least in the fresh state. The following notes are from the related A. calamus - the fresh root can be poisonous[7]. When using the plant medicinally, the isolated essential oil should not be used[165].",not recommended due to safety concerns,high
10,Indian Horse Chestnut,Acrid; Anthelmintic; Antirheumatic; Astringent; Narcotic; Stomachic,"The seed is rich in saponins[20, 65]. Although poisonous, saponins are poorly absorbed by the human body and so most pass through without harm. Saponins are quite bitter and can be found in many common foods such as some beans. They can be removed by carefully leaching the seed or flour in running water. Thorough cooking, and perhaps changing the cooking water once, will also normally remove most of them. However, it is not advisable to eat large quantities of food that contain saponins. Saponins are much more toxic to some creatures, such as fish, and hunting tribes have traditionally put large quantities of them in streams, lakes etc in order to stupefy or kill the fish[K].",not recommended due to safety concerns,high
11,Fool's Parsley,Anticonvulsant; Antidiarrhoeal; Sedative; Stomachic,"The entire plant is poisonous though less so than Conium maculatum (q.v.)[4, 10, 19]. Small amounts can cause pain, confusion of vision and vomiting[268]. The dried plant might be safe to eat[10].",not recommended due to safety concerns,high
12,"African Lily, Lily of the nile",Cardiac; Stomachic,None known,unknown,low
13,Korean Mint,Antibacterial; Antifungal; Antipyretic; Aromatic; Cancer; Carminative; Diaphoretic; Febrifuge; Refrigerant; Stomachic,None known,unknown,low
14,"Giant Hyssop, Nettleleaf giant hyssop",Analgesic; Antirheumatic; Stomachic,None known,unknown,low
15,"Akebia, Chocolate vine, Fiveleaf Akebia, Chocolate Vine",Anodyne; Antiphlogistic; Bitter; Cancer; Contraceptive; Depurative; Diaphoretic; Diuretic; Emmenagogue; Febrifuge; Galactogogue; Laxative; Resolvent; Stimulant; Stomachic; Urinary; Vulnerary,None known,topical,low
16,"Wild Leek, Broadleaf wild leek",Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cholagogue; Diaphoretic; Diuretic; Expectorant; Febrifuge; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"Although no individual reports regarding this species have been seen, there have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of certain members of this genus. Dogs seem to be particularly susceptible[76].",unknown,medium
17,"Onion, Garden onion",Anthelmintic; Antiinflammatory; Antiseptic; Antispasmodic; Appetizer; Carminative; Diuretic; Expectorant; Febrifuge; Homeopathy; Hypoglycaemic; Hypotensive; Lithontripic; Skin; Stings; Stomachic; Tonic,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this plant. Dogs seem to be particularly susceptible[76]. Hand eczema may occur with frequent handling. May interfere with drug control of blood sugar [301].","food,oil,topical",medium
18,Potato Onion,Anthelmintic; Antiinflammatory; Antiseptic; Antispasmodic; Carminative; Diuretic; Expectorant; Febrifuge; Hypoglycaemic; Hypotensive; Lithontripic; Skin; Stomachic; Tonic,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this plant. Dogs seem to be particularly susceptible[76].","food,oil,topical",medium
19,Shallot,Alterative; Anthelmintic; Antiinflammatory; Antiseptic; Antispasmodic; Astringent; Carminative; Diuretic; Expectorant; Febrifuge; Hypoglycaemic; Hypotensive; Lithontripic; Nutritive; Skin; Stings; Stomachic; Tonic; Vulnerary,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this plant. Dogs seem to be particularly susceptible[76].",topical,medium
20,"Tree Onion, Walking Onion",Anthelmintic; Antiinflammatory; Antiseptic; Antispasmodic; Carminative; Diuretic; Expectorant; Febrifuge; Hypoglycaemic; Hypotensive; Lithontripic; Skin; Stomachic; Tonic,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this plant. Dogs seem to be particularly susceptible[76].","food,oil,topical",medium
21,Welsh Onion,Antibacterial; Antifungal; Antipyretic; Diuretic; Expectorant; Stomachic; Vitamin C,"Although no individual reports regarding this species have been seen, there have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of certain members of this genus. Dogs seem to be particularly susceptible[76].","food,oil",medium
22,"Leek, Garden leek",Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cholagogue; Diaphoretic; Diuretic; Expectorant; Febrifuge; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"Although no individual reports regarding this species have been seen, there have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of certain members of this genus. Dogs seem to be particularly susceptible[76].",unknown,medium
23,"Garlic, Cultivated garlic",Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Hypoglycaemic; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76]. Avoid with anticlotting medication. Breastfeeding may worsen baby's colic. Avoid several weeks prior to surgery. Bad breath!! [301].",not recommended due to safety concerns,medium
24,Serpent Garlic,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Cancer; Cholagogue; Diaphoretic; Diuretic; Dysentery; Expectorant; Febrifuge; Stimulant; Stings; Stomachic; Tonic; Vasodilator,"There have been cases of poisoning caused by the consumption, in large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76].",unknown,medium
25,"Garlic Chives, Chinese chives, Oriental Chives,",Antibacterial; Cardiac; Digestive; Stomachic; Tonic; Urinary,"Although no individual reports regarding this species have been seen, there have been cases of poisoning caused by the consumption, in very large quantities and by some mammals, of certain members of this genus. Dogs seem to be particularly susceptible[76].","food,oil",medium
26,Wild Garlic,Anthelmintic; Antiasthmatic; Anticholesterolemic; Antiseptic; Antispasmodic; Astringent; Cholagogue; Depurative; Diaphoretic; Disinfectant; Diuretic; Expectorant; Febrifuge; Hypotensive; Rubefacient; Stimulant; Stomachic; Tonic; Vasodilator,"There have been cases of poisoning caused by the consumption, in very large quantities and by some mammals, of this species. Dogs seem to be particularly susceptible[76].",topical,medium
27,White Alder,Astringent; Birthing aid; Diaphoretic; Emetic; Haemostatic; Skin; Stomachic; TB; Tonic,The freshly harvested inner bark is emetic but is alright once it has been dried[172].,"capsule_or_powder,topical",medium
28,"Red Alder, Oregon Alder",Anodyne; Appetizer; Astringent; Cathartic; Cytostatic; Eczema; Febrifuge; Skin; Stomachic; TB; Tonic,The freshly harvested inner bark is emetic but is alright once it has been dried[172].,"capsule_or_powder,topical",medium
29,Speckled Alder,Alterative; Anodyne; Astringent; Cathartic; Emetic; Febrifuge; Odontalgic; Ophthalmic; Stomachic; Tonic,None known,unknown,low

In [56]:
mvp_dataset[["Common Name", "preparation_type", "warning_level"]].head(30)

,Common Name,preparation_type,warning_level
0,"Musk Mallow,Musk Okra","oil,topical",low
1,"Grand Fir, Giant Fir, Lowland White Fir",topical,low
2,Himalayan Fir,unknown,low
3,"China Jute, Velvetleaf, Butterprint Buttonweed Jute, China Mallow, Indian Velvet Leaf",topical,low
4,"Sweet Acacia, Perfume Acacia, Huisache",topical,medium
5,Musk Milfoil,unknown,low
6,Siberian Yarrow,unknown,low
7,Basil Thyme,topical,low
8,Sweet Flag - Calamus,not recommended due to safety concerns,high
9,"Grass-leaved Sweet Rush, Japanese Sweet Flag, Dwarf Sweet Flag",not recommended due to safety concerns,high
10,Indian Horse Chestnut,not recommended due to safety concerns,high
11,Fool's Parsley,not recommended due to safety concerns,high
12,"African Lily, Lily of the nile",unknown,low
13,Korean Mint,unknown,low
14,"Giant Hyssop, Nettleleaf giant hyssop",unknown,low
15,"Akebia, Chocolate vine, Fiveleaf Akebia, Chocolate Vine",topical,low
16,"Wild Leek, Broadleaf wild leek",unknown,medium
17,"Onion, Garden onion","food,oil,topical",medium
18,Potato Onion,"food,oil,topical",medium
19,Shallot,topical,medium
20,"Tree Onion, Walking Onion","food,oil,topical",medium
21,Welsh Onion,"food,oil",medium
22,"Leek, Garden leek",unknown,medium
23,"Garlic, Cultivated garlic",not recommended due to safety concerns,medium
24,Serpent Garlic,unknown,medium
25,"Garlic Chives, Chinese chives, Oriental Chives,","food,oil",medium
26,Wild Garlic,topical,medium
27,White Alder,"capsule_or_powder,topical",medium
28,"Red Alder, Oregon Alder","capsule_or_powder,topical",medium
29,Speckled Alder,unknown,low

In [57]:
mvp_dataset["warning_level"].value_counts()

warning_level
low       109
high       69
medium     64
Name: count, dtype: int64

In [58]:
mvp_dataset["preparation_type"].value_counts()

preparation_type
not recommended due to safety concerns                              84
unknown                                                             73
topical                                                             41
food,oil,topical                                                     4
food,oil                                                             4
capsule_or_powder                                                    4
oil                                                                  4
food                                                                 3
cream_or_onitment                                                    3
food,topical                                                         3
capsule_or_powder,topical                                            2
food,tea                                                             2
capsule_or_powder,food                                               2
oil,tea                                                              2
oil,topical                                                          1
cream_or_onitment,topical                                            1
capsule_or_powder,cream_or_onitment,extract,food,oil,tea,topical     1
capsule_or_powder,food,oil                                           1
food,juice_or_gel                                                    1
food,tea,topical                                                     1
capsule_or_powder,extract,food,oil                                   1
tea                                                                  1
juice_or_gel,topical                                                 1
poultice                                                             1
capsule_or_powder,food,oil,tea                                       1
Name: count, dtype: int64

In [59]:
mvp_dataset.to_csv("../data/processed/mvp_herbal_dataset_v3.csv", index=False)